apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monolithic-app
  template:
    metadata:
      labels:
        app: monolithic-app
    spec:
      containers:
        - name: nginx
          image: elhareth/my-docker-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: php
          image: elhareth/my-docker-php:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html
        - name: mysql
          image: elhareth/my-docker-mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "laravel"
            - name: MYSQL_USER
              value: "laraveluser"
            - name: MYSQL_PASSWORD
              value: "laravelpassword"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data-pvc
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
# Nginx ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        server_name localhost;
        root /var/www/html/public;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }

        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
    }
---
# Service for the monolithic app
apiVersion: v1
kind: Service
metadata:
  name: monolithic-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: monolithic-app