version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        working_dir: /var/www/html
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000" 


    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpassword
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "4306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
